language: node_js
env:
  - NODE_VERSION="12.8.1"
before_install:
  - nvm install $NODE_VERSION
git:
  depth: 1
install:
  - yarn
script:
  - yarn run build
cache:
  yarn: true
  directories:
    - ./node_modules/
