language: node_js
env:
  - NODE_VERSION="12.8.1"
before_install:
  - nvm install $NODE_VERSION
git:
  depth: 1
install:
  - yarn
script:
  - node --max_old_space_size=4096 node_modules/@angular/cli/bin/ng build --prod
cache:
  yarn: true
  directories:
    - ./node_modules/
