version: "3"

services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      discovery.type: "single-node"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 30s
      timeout: 10s
      retries: 3
  indigo-api:
    image: asurapro/indigo-api:latest
    ports:
      - "9000:9000"
    links:
      - elasticsearch
    depends_on:
      - elasticsearch
    restart: on-failure
    environment:
      APPLICATION_SECRET: "0><>0zv0oG>JH6>YHq4Hs=5x;ht8VB>x`_lOWo<cb309F3n`k;gy1j;i[cd;zE>u"
  indigo:
    image: asurapro/indigo:latest
    ports:
      - "80:80"
    links:
      - indigo-api
